services:
  app:
    container_name: photo_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://photo_admin:photo_password@postgres:5432/photo_albums
      NEXT_PUBLIC_APP_URL: https://albums.nastuiron.fr
      JWT_SECRET: "un_secret_ultra_long_et_random"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nastuiron_proxy
    ports:
      - "3001:3000"

  postgres:
    image: postgres:16
    container_name: photo_albums_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: photo_admin
      POSTGRES_PASSWORD: photo_password
      POSTGRES_DB: photo_albums
    ports:
      - "5433:5432"
    volumes:
      - photo_albums_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U photo_admin -d photo_albums"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - nastuiron_proxy

volumes:
  photo_albums_data:

networks:
  nastuiron_proxy:
    name: nastuiron_proxy
